shopping_mart/G_shopper/urls.py
from django.urls import path 
from G_shopper import views
from .views import  PasswordsChangeView
from django.contrib.auth import views as auth_views



app_name = 'G_shopper'

urlpatterns = [
    path('login/', views.userLogin, name='login'),
    # path('',views.base_page,name='base'),
    path('home/',views.home_page,name='home'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('loggedout/',views.logoutuser,name='loggedout'),
    path('registration/',views.UserRegister.as_view(),name='register'),
    path('mycart/',views.add_cart,name='cart'),
    path('cart/',views.cart_list,name='addcart'),
    path('deletefromcart/',views.delete_cart_item,name='delete-from-cart'),
    path('updatecart/',views.update_cart_item,name='update-cart'),
    path('deleteCart/',views.DeleteCart.as_view(),name='DeleteCart'),
    path('add-wishlist/',views.add_wishlist, name='add_wishlist'),
    path('my-wishlist/',views.my_wishlist, name='my_wishlist'),
    path("delete/",views.DeleteWishlist.as_view(),name="DeleteWishlist"),
    path('product/<int:product_id>',views.product_detail, name='product_detail'),
    path('coupon/',views.couponcalculate, name='couponcal'),
    path('checkout/',views.checkout,name='checkout'),
    path('address/',views.Add_address.as_view(),name='address'),    
    path('placeorder/',views.placeorder,name='placeorder'),
    path('stripe/',views.stripe_order,name='stripe'),
    path('cod/',views.cashondelivery,name='cod'),
    # path('category/',views.category_filter,name='category'),
    path('price/',views.price_filter,name='price'),
    # path('filter/',views.filter,name='filter'),
    path('order_track/',views.tracking_order,name='order_track'),
    path('check_order/',views.check_order,name='check_order'),
    path('contact/',views.contact_us,name='contact'),
    path('my_order/',views.my_order,name='my_order'),
    path('detailed_order/<int:order_id>',views.detailed_order.as_view(),name='detailed_order'),
    path('my_account/',views.my_account,name='my_account'),
    path('edit-profile/',views.edit_profile, name='edit-profile'),
    path('password/',PasswordsChangeView.as_view(template_name='changepassword.html'),name='password'),
    path('password_success',views.password_success,name='password_success'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('about_us/',views.cms_content,name='about_us'),
    path('privacy_policy/',views.privacy_policy,name='privacy_policy'),
    path('mail_template/',views.mail_template,name='mail_template'),
    path('order_mail_template/',views.order_mail_template,name='order_mail_template'),

    ]

shopping_mart/customAdminPanel/urls.py
from os import stat
from unicodedata import category
from django.urls import path 
from customAdminPanel import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required 

app_name = 'customAdminPanel'

urlpatterns = [
    path('login/', views.adminLogin, name='admin_login'),
    path('',views.index,name='index'),
    path('logout/',views.logoutUser,name='logoutuser'),
    path('banner/',views.banner_check, name='banner'),
    path('banner_form/',views.BannerField.as_view(),name='banner_form'),
    path("delete/",views.DeleteBanner.as_view(),name="Delete"),
    path("edit/<int:id>" ,views.EditBanner.as_view(),name="Edit"),
    path('category/',views.category_check, name='category'),
    path('category_form',views.CategoryField.as_view(),name='category_form'),
    path("Delete_category/",views.DeleteCategory.as_view(),name="Delete_category"),
    path("editCategory/<int:id>" ,views.EditCategory.as_view(),name="EditCategory"),
    path('cms/',views.cms_check, name='cms'),
    path('cms_form/',views.CmsField.as_view(),name='cms_form'),
    path("Delete_cms/",views.DeleteCms.as_view(),name="Delete_cms"),
    path("editCms/<int:id>" ,views.EditCms.as_view(),name="EditCms"),
    path('configuration/',views.configuration_check, name='configuration'),
    path('configuration_form/',views.ConfigurationField.as_view(),name='configuration_form'),
    path('contactUs/',views.contactUs_check, name='contactUs'),
    path('contactUs_form/',views.ContactUsField.as_view(),name='contactUs_form'),
    path('coupon/',views.coupon_check, name='coupon'),
    path('coupon_form/',views.CouponField.as_view(),name='coupon_form'),
    path("coupondelete/",views.DeleteCoupon.as_view(),name="Delete_coupon"),
    path("editCoupon/<int:id>" ,views.EditCoupon.as_view(),name="EditCoupon"),
    path('email/',views.email_check, name='email'),
    path('email_form/',views.EmailField.as_view(),name='email_form'),
    path('emaildelete/',views.DeleteEmail.as_view(),name='emaildelete'),
    path("editEmail/<int:id>" ,views.EditEmail.as_view(),name="EditEmail"),
    path('orderDetail/',views.orderDetail_check, name='orderDetail'),
    path('orderDetail_form/',views.OrderDetailField.as_view(),name='orderDetail_form'),
    path('detail_order/<int:order_id>',views.detail_order.as_view(),name='detail_order'),
    path('paymentGateway/',views.paymentGateway_check, name='paymentGateway'),
    path('paymentGateway_form/',views.PaymentGatewayField.as_view(),name='paymentGateway_form'),
    path('product/',views.product_check, name='product'),
    path('product_form/',views.ProductField.as_view(),name='product_form'),
    path("productdelete/",views.DeleteProduct.as_view(),name="Delete_product"),
    path("editProduct/<int:id>" ,views.EditProduct.as_view(),name="EditProduct"),
    path('productAttributes/',views.productAttributes_check, name='productAttributes'),
    path('productAttributes_form/',views.ProductAttributesField.as_view(),name='productAttributes_form'),
    path("productAttributesdelete/",views.DeleteProductAttributes.as_view(),name="Delete_productAttributes"),
    path("editProductAttributes/<int:id>" ,views.EditProductAttributes.as_view(),name="EditProductAttributes"),
    path('productAttributesAssoc/',views.productAttributesAssoc_check, name='productAttributesAssoc'),
    path('productAttributesAssoc_form/',views.ProductAttributesAssocField.as_view(),
    name='productAttributesAssoc_form'),
    path('ajax/productAttributesValue/',views.getAttributeValues, name='productAttributesValue'),
    path('productAttributesValues/',views.productAttributesValues_check, name='productAttributesValues'),
    path('productAttributesValues_form/',views.ProductAttributesValuesField.as_view(),name='productAttributesValues_form'),
    path('productCategory/',views.productCategory_check, name='productCategory'),
    path('productCategory_form/',views.ProductCategoryField.as_view(),name='productCategory_form'),
    path("productCategorydelete/",views.DeleteProductCategory.as_view(),name="Delete_productCategory"),
    path("editProductCategory/<int:id>" ,views.EditProductCategory.as_view(),name="EditProductCategory"),
    path('productImages/',views.productImages_check, name='productImages'),
    path('productImages_form/',views.ProductImagesField.as_view(),name='productImages_form'),
    path("productImagesdelete/",views.DeleteProductImage.as_view(),name="Delete_productImage"),
    path("editProductImage/<int:id>" ,views.EditProductImage.as_view(),name="EditProductImage"),
    path('usedCoupon/',views.usedCoupon_check, name='usedCoupon'),
    path('usedCoupon_form/',views.UsedCouponField.as_view(),name='usedCoupon_form'),
    path('user/',views.user_check, name='user'),
    path('user_form/',views.UserField.as_view(),name='user_form'),
    path('userAddress/',views.userAddress_check, name='userAddress'),
    path('userAddress_form/',views.UserAddressField.as_view(),name='userAddress_form'),
    path('userOrder/',views.userOrder_check, name='userOrder'),
    path('userOrder_form/',views.UserOrderField.as_view(),name='userOrder_form'),
    path("userOrderdelete/",views.DeleteUserOrder.as_view(),name="Delete_userOrder"),
    path("edituserOrder/<int:id>" ,views.EditUserOrder.as_view(),name="Edit_userOrder"),
    path('userWishlist/',views.userWishlist_check, name='userWishlist'),
    path('userWishlist_form/',views.UserWishlistField.as_view(),name='userWishlist_form'),
    path("userWishlistdelete/",views.DeleteuserWishlist.as_view(),name="Delete_userWishlist"),
    

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/shopping_mart/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
 
app_name = 'customAdminPanel'
app_name = 'G_shopper'

urlpatterns = [
    path('adminpanel/', include('customAdminPanel.urls')),
    path('admin/',admin.site.urls,name='django-admin'),
    path('', include('G_shopper.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/G_shopper/models.py
from django.db import models

# Create your models here.

shopping_mart/G_shopper/templates/about_us.html
{% extends 'base.html' %}

{% block content %}

{% for i in cms%}
<h1 style="text-align:center;">{{i.title}}</h1>
<h2 style="text-align:center;">{{i.content|safe}}</h2>



{% endfor %}

{% endblock %}

shopping_mart/G_shopper/templates/based.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Home | E-Shopper</title>
	<link href="/static/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/css/font-awesome.min.css" rel="stylesheet">
	<link href="/static/css/prettyPhoto.css" rel="stylesheet">
	<link href="/static/css/price-range.css" rel="stylesheet">
	<link href="/static/css/animate.css" rel="stylesheet">
	<link href="/static/css/main.css" rel="stylesheet">
	<link href="/static/css/responsive.css" rel="stylesheet">
	<!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
	<link rel="shortcut icon" href="/static/images/ico/favicon.ico">
	<link rel="/static/apple-touch-icon-precomposed" sizes="144x144"
		href="/static/images/ico/apple-touch-icon-144-precomposed.png">
	<link rel="/static/apple-touch-icon-precomposed" sizes="114x114"
		href="/static/images/ico/apple-touch-icon-114-precomposed.png">
	<link rel="/static/apple-touch-icon-precomposed" sizes="72x72"
		href="/static/images/ico/apple-touch-icon-72-precomposed.png">
	<link rel="/static/apple-touch-icon-precomposed" href="/static/images/ico/apple-touch-icon-57-precomposed.png">
	<style>
		li {list-style-type: none;
font-size: 16pt;
}
.mail {
margin: auto;
padding-top: 10px;
padding-bottom: 10px;
width: 400px;
background : 
#D8F1F8;
border: 1px soild 
silver;
}
.mail h2 {
margin-left: 38px;
}
input {
font-size: 20pt;
}
input:focus, textarea:focus{
background-color: 
lightyellow;
}
input submit {
font-size: 12pt;
}
.rq {
color: 
#FF0000;
font-size: 10pt;
}
	</style>
</head>
<!--/head-->

<body  onload='document.form1.text1.focus()'>
	<header id="header">
		<!--header-->
		<div class="header_top">
			<!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<!-- <ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul> -->
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<!-- <ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul> -->
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/header_top-->

		<div class="header-middle">
			<!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="{% url 'G_shopper:home' %}"><img src="/static/images/home/logo.png" alt="" /></a>
							

						</div>
						<div class="btn-group pull-right">
							<!-- <div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle india"
									data-toggle="dropdown">
									INDIA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Mumbai</a></li>
									<li><a href="#">Delhi</a></li>
								</ul>
							</div>

							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle india"
									data-toggle="dropdown">
									Rupees
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Rupees</a></li>
								</ul>
							</div> -->
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<!-- <li><a href="{% url 'G_shopper:my_account' %}"><i class="fa fa-user"></i> My Account</a>
								</li>
								<li><a href="{% url 'G_shopper:my_order' %}"><i class="fa fa-user"></i> My Order</a>
								</li>
								<li><a href="{% url 'G_shopper:my_wishlist' %}"><i class="fa fa-star"></i> Wishlist</a>
								</li> -->
								<!-- <li><a href="{% url 'G_shopper:checkout' %}"><i class="fa fa-crosshairs"></i>
                                        Checkout</a></li> -->
								<!-- <li><a href="{% url 'G_shopper:addcart' %}"><i class="fa fa-shopping-cart"></i>
										Cart(<span class="cart-list">{{request.session.cartdata|length}}</span>)</a>
								</li> -->
								<!-- <li><a href=""><i class="fa fa-lock"></i> log in</a></li> -->
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/header-middle-->

		<div class="header-bottom">
			<!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse"
								data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'G_shopper:home' %}" class="active">Home</a></li>
								<li><a href="{% url 'G_shopper:contact' %}">Contact</a></li>
								<!-- <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a> -->
								<ul role="menu" class="sub-menu">
									<!-- <li><a href="shop.html">Products</a></li>
										<li><a href="product-details.html">Product Details</a></li>  -->
									<li><a href="checkout.html">Checkout</a></li>
									<li><a href="cart.html">Cart({{totalitems}})</a></li>
									<li><a href="login.html">Login</a></li>
								</ul>
								</li>
								<!-- <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a> -->
								<ul role="menu" class="sub-menu">
									<!-- <li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li> 
								<li><a href="404.html">404</a></li>
								<li><a href="contact-us.html">Contact</a></li> -->
								</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<!-- <div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div> -->
					</div>
				</div>
			</div>
		</div>
		<!--/header-bottom-->
	</header>
	<!--/header-->

		{% block content %}


		{% endblock %}

		<footer id="footer">
			<!--Footer-->
			<div class="footer-top">
				<div class="container">
					<div class="row">
						<div class="col-sm-2">
							<div class="companyinfo">
								<h2><span>e</span>-shopper</h2>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
							</div>
						</div>
						<div class="col-sm-7">
							<div class="col-sm-3">
								<div class="video-gallery text-center">
									<a href="#">
										<div class="iframe-img">
											<img src="/static/images/home/iframe1.png" alt="" />
										</div>
										<div class="overlay-icon">
											<i class="fa fa-play-circle-o"></i>
										</div>
									</a>
									<p>Circle of Hands</p>
									<h2>24 DEC 2014</h2>
								</div>
							</div>

							<div class="col-sm-3">
								<div class="video-gallery text-center">
									<a href="#">
										<div class="iframe-img">
											<img src="/static/images/home/iframe2.png" alt="" />
										</div>
										<div class="overlay-icon">
											<i class="fa fa-play-circle-o"></i>
										</div>
									</a>
									<p>Circle of Hands</p>
									<h2>24 DEC 2014</h2>
								</div>
							</div>

							<div class="col-sm-3">
								<div class="video-gallery text-center">
									<a href="#">
										<div class="iframe-img">
											<img src="/static/images/home/iframe3.png" alt="" />
										</div>
										<div class="overlay-icon">
											<i class="fa fa-play-circle-o"></i>
										</div>
									</a>
									<p>Circle of Hands</p>
									<h2>24 DEC 2014</h2>
								</div>
							</div>

							<div class="col-sm-3">
								<div class="video-gallery text-center">
									<a href="#">
										<div class="iframe-img">
											<img src="/static/images/home/iframe4.png" alt="" />
										</div>
										<div class="overlay-icon">
											<i class="fa fa-play-circle-o"></i>
										</div>
									</a>
									<p>Circle of Hands</p>
									<h2>24 DEC 2014</h2>
								</div>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="address">
								<img src="/static/images/home/map.png" alt="" />
								<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="footer-widget">
				<div class="container">
					<div class="row">
						<div class="col-sm-2">
							<div class="single-widget">
								<h2>Service</h2>
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#">Online Help</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Order Status</a></li>
									<li><a href="#">Change Location</a></li>
									<li><a href="#">FAQ’s</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-2">
							<div class="single-widget">
								<h2>Quock Shop</h2>
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#">T-Shirt</a></li>
									<li><a href="#">Mens</a></li>
									<li><a href="#">Womens</a></li>
									<li><a href="#">Gift Cards</a></li>
									<li><a href="#">Shoes</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-2">
							<div class="single-widget">
								<h2>Policies</h2>
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#">Terms of Use</a></li>
									<li><a href="#">Privecy Policy</a></li>
									<li><a href="#">Refund Policy</a></li>
									<li><a href="#">Billing System</a></li>
									<li><a href="#">Ticket System</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-2">
							<div class="single-widget">
								<h2>About Shopper</h2>
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#">Company Information</a></li>
									<li><a href="#">Careers</a></li>
									<li><a href="#">Store Location</a></li>
									<li><a href="#">Affillate Program</a></li>
									<li><a href="#">Copyright</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-3 col-sm-offset-1">
							<!-- <div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div> -->
						</div>

					</div>
				</div>
			</div>

			<div class="footer-bottom">
				<div class="container">
					<div class="row">
						<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
						<p class="pull-right">Designed by <span><a target="_blank"
									href="http://www.themeum.com">Themeum</a></span></p>
					</div>
				</div>
			</div>

		</footer>
		<!--/Footer-->



		<script src="/static/js/jquery.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>
		<script src="/static/js/jquery.scrollUp.min.js"></script>
		<script src="/static/js/price-range.js"></script>
		<script src="/static/js/jquery.prettyPhoto.js"></script>
		<script src="/static/js/main.js"></script>
</body>

</html>

shopping_mart/G_shopper/templates/mail_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    <p>
        {{data|safe}}
    </p>
</body>

</html>

shopping_mart/G_shopper/templates/my_order.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align:center;">My Order's</h1> <br>
<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="col-sm-12">
                          
                        </div>
                        <!-- <form action="{% url 'customAdminPanel:userOrder_form' %}">
                            <button  type="submit" class="btn btn-primary btn-block">Sign Out</button>
                            <button style="float: right; width: 150px; height: 40px;" type="submit"
                                class="btn btn-block btn-primary">Add</button>
                        </form> -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                              <thead>
                                <tr>
                                  <!-- <th>id</th> -->
                                  <th>order_id</th>
                                  <th>Image</th>
                                  <th>Product Name</th>
                                  <th>Product Price</th>
                                  <th>Quantity</th>

                                  <!-- <th scope="col" colspan="2">Action</th> -->
                                </tr>
                              </thead>
                              <tbody>
                                {% for i in order_data %}
                                <tr>
                                  <!-- <td>{{i.id}}</td> -->
                                  <td>{{i.order_id}}</td>
                                  
                                  <td><img src="{{ i.image_path.url }}" style="height: 30px" width="30px" alt=""></td>
                                  
                                  <td>{{i.product_id}}</td> 
                                  <td>{{i.amount}}</td>
                                  <td>{{i.quantity}}</td>
                                  

                                  <!-- <td>
                                    <button type="submit" value="Delete" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deletemodal">
                                      Delete
                                    </button>
                                    <div class="modal fade" id="deletemodal">
                                      <div class="modal-dialog">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <h4 class="modal-title">Delete</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                            </button>
                                          </div>
                                          <form action="{% url 'customAdminPanel:Delete_userOrder' %}" method="POST">
                                            {% csrf_token %}
                                            <div class="modal6-body">
                                              <input type="hidden" name="id" value={{i.id}}>
                                              <h4>Do you want to delete this data??</h4>
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                              <button type="submit" class="btn btn-danger">Ok
                                              </button>
                                            </div>
                                        </div>
                                      </div>
                                    </div>
                                    </form>
                                  </td>                     -->
                                </tr>
                                {% endfor %}
                              </tbody>
                            </table>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

shopping_mart/G_shopper/templates/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="." method="post">
{{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Change my password" /></p>
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

shopping_mart/G_shopper/templates/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
{% endblock %}

shopping_mart/G_shopper/templates/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url "G_shopper:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username}}

shopping_mart/G_shopper/templates/password_reset_form.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Forgotten your password?</h1>
<p>Enter your e-mail address to obtain a new password.</p>
<form action="." method="post">
{{ form.as_p }}
<p><input type="submit" value="Send e-mail"></p>
{% csrf_token %}
</form>
{% endblock %}

shopping_mart/G_shopper/templates/password_success.html
{%  extends 'base.html' %}
{% block content %}
{% load static %}

<h1 style="text-align:center;">Your Password has Changed Successfully...</h1>
<br/><br/>



{% endblock %}

shopping_mart/G_shopper/templates/privacy_policy.html
{% extends 'base.html' %}

{% block content %}

<p>{{cms|safe}}</p>

{% endblock %}

shopping_mart/G_shopper/templates/stripe.html
{% extends 'base.html' %}

{% block content %}

<a href="{{pay}}"><button>Stripe</button></a>

{% endblock %}

shopping_mart/G_shopper/templates/update_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1" align="center">Edit Profile</h3>
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-9">
			{% if msg %}
			<p class="text-success">{{msg}}</p>
			{% endif %}
			<table class="table table-bordered">
				<form method="post">
					{% csrf_token %}
					{{form.as_table}}
					<tr>
						<td colspan="2">
							<input type="submit" value="Save" class="btn btn-primary" />
						</td>
					</tr>
				</form>
			</table>
		</div>
	</div>
</main>
{% endblock %}