shopping_mart/G_shopper/urls.py
from django.urls import path 
from G_shopper import views
from .views import  PasswordsChangeView
from django.contrib.auth import views as auth_views



app_name = 'G_shopper'

urlpatterns = [
    path('login/', views.userLogin, name='login'),
    # path('',views.base_page,name='base'),
    path('home/',views.home_page,name='home'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('loggedout/',views.logoutuser,name='loggedout'),
    path('registration/',views.UserRegister.as_view(),name='register'),
    path('mycart/',views.add_cart,name='cart'),
    path('cart/',views.cart_list,name='addcart'),
    path('deletefromcart/',views.delete_cart_item,name='delete-from-cart'),
    path('updatecart/',views.update_cart_item,name='update-cart'),
    path('deleteCart/',views.DeleteCart.as_view(),name='DeleteCart'),
    path('add-wishlist/',views.add_wishlist, name='add_wishlist'),
    path('my-wishlist/',views.my_wishlist, name='my_wishlist'),
    path("delete/",views.DeleteWishlist.as_view(),name="DeleteWishlist"),
    path('product/<int:product_id>',views.product_detail, name='product_detail'),
    path('coupon/',views.couponcalculate, name='couponcal'),
    path('checkout/',views.checkout,name='checkout'),
    path('address/',views.Add_address.as_view(),name='address'),    
    path('placeorder/',views.placeorder,name='placeorder'),
    path('stripe/',views.stripe_order,name='stripe'),
    path('cod/',views.cashondelivery,name='cod'),
    # path('category/',views.category_filter,name='category'),
    path('price/',views.price_filter,name='price'),
    # path('filter/',views.filter,name='filter'),
    path('order_track/',views.tracking_order,name='order_track'),
    path('check_order/',views.check_order,name='check_order'),
    path('contact/',views.contact_us,name='contact'),
    path('my_order/',views.my_order,name='my_order'),
    path('detailed_order/<int:order_id>',views.detailed_order.as_view(),name='detailed_order'),
    path('my_account/',views.my_account,name='my_account'),
    path('edit-profile/',views.edit_profile, name='edit-profile'),
    path('password/',PasswordsChangeView.as_view(template_name='changepassword.html'),name='password'),
    path('password_success',views.password_success,name='password_success'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('about_us/',views.cms_content,name='about_us'),
    path('privacy_policy/',views.privacy_policy,name='privacy_policy'),
    path('mail_template/',views.mail_template,name='mail_template'),
    path('order_mail_template/',views.order_mail_template,name='order_mail_template'),

    ]

shopping_mart/customAdminPanel/urls.py
from os import stat
from unicodedata import category
from django.urls import path 
from customAdminPanel import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required 

app_name = 'customAdminPanel'

urlpatterns = [
    path('login/', views.adminLogin, name='admin_login'),
    path('',views.index,name='index'),
    path('logout/',views.logoutUser,name='logoutuser'),
    path('banner/',views.banner_check, name='banner'),
    path('banner_form/',views.BannerField.as_view(),name='banner_form'),
    path("delete/",views.DeleteBanner.as_view(),name="Delete"),
    path("edit/<int:id>" ,views.EditBanner.as_view(),name="Edit"),
    path('category/',views.category_check, name='category'),
    path('category_form',views.CategoryField.as_view(),name='category_form'),
    path("Delete_category/",views.DeleteCategory.as_view(),name="Delete_category"),
    path("editCategory/<int:id>" ,views.EditCategory.as_view(),name="EditCategory"),
    path('cms/',views.cms_check, name='cms'),
    path('cms_form/',views.CmsField.as_view(),name='cms_form'),
    path("Delete_cms/",views.DeleteCms.as_view(),name="Delete_cms"),
    path("editCms/<int:id>" ,views.EditCms.as_view(),name="EditCms"),
    path('configuration/',views.configuration_check, name='configuration'),
    path('configuration_form/',views.ConfigurationField.as_view(),name='configuration_form'),
    path('contactUs/',views.contactUs_check, name='contactUs'),
    path('contactUs_form/',views.ContactUsField.as_view(),name='contactUs_form'),
    path('coupon/',views.coupon_check, name='coupon'),
    path('coupon_form/',views.CouponField.as_view(),name='coupon_form'),
    path("coupondelete/",views.DeleteCoupon.as_view(),name="Delete_coupon"),
    path("editCoupon/<int:id>" ,views.EditCoupon.as_view(),name="EditCoupon"),
    path('email/',views.email_check, name='email'),
    path('email_form/',views.EmailField.as_view(),name='email_form'),
    path('emaildelete/',views.DeleteEmail.as_view(),name='emaildelete'),
    path("editEmail/<int:id>" ,views.EditEmail.as_view(),name="EditEmail"),
    path('orderDetail/',views.orderDetail_check, name='orderDetail'),
    path('orderDetail_form/',views.OrderDetailField.as_view(),name='orderDetail_form'),
    path('detail_order/<int:order_id>',views.detail_order.as_view(),name='detail_order'),
    path('paymentGateway/',views.paymentGateway_check, name='paymentGateway'),
    path('paymentGateway_form/',views.PaymentGatewayField.as_view(),name='paymentGateway_form'),
    path('product/',views.product_check, name='product'),
    path('product_form/',views.ProductField.as_view(),name='product_form'),
    path("productdelete/",views.DeleteProduct.as_view(),name="Delete_product"),
    path("editProduct/<int:id>" ,views.EditProduct.as_view(),name="EditProduct"),
    path('productAttributes/',views.productAttributes_check, name='productAttributes'),
    path('productAttributes_form/',views.ProductAttributesField.as_view(),name='productAttributes_form'),
    path("productAttributesdelete/",views.DeleteProductAttributes.as_view(),name="Delete_productAttributes"),
    path("editProductAttributes/<int:id>" ,views.EditProductAttributes.as_view(),name="EditProductAttributes"),
    path('productAttributesAssoc/',views.productAttributesAssoc_check, name='productAttributesAssoc'),
    path('productAttributesAssoc_form/',views.ProductAttributesAssocField.as_view(),
    name='productAttributesAssoc_form'),
    path('ajax/productAttributesValue/',views.getAttributeValues, name='productAttributesValue'),
    path('productAttributesValues/',views.productAttributesValues_check, name='productAttributesValues'),
    path('productAttributesValues_form/',views.ProductAttributesValuesField.as_view(),name='productAttributesValues_form'),
    path('productCategory/',views.productCategory_check, name='productCategory'),
    path('productCategory_form/',views.ProductCategoryField.as_view(),name='productCategory_form'),
    path("productCategorydelete/",views.DeleteProductCategory.as_view(),name="Delete_productCategory"),
    path("editProductCategory/<int:id>" ,views.EditProductCategory.as_view(),name="EditProductCategory"),
    path('productImages/',views.productImages_check, name='productImages'),
    path('productImages_form/',views.ProductImagesField.as_view(),name='productImages_form'),
    path("productImagesdelete/",views.DeleteProductImage.as_view(),name="Delete_productImage"),
    path("editProductImage/<int:id>" ,views.EditProductImage.as_view(),name="EditProductImage"),
    path('usedCoupon/',views.usedCoupon_check, name='usedCoupon'),
    path('usedCoupon_form/',views.UsedCouponField.as_view(),name='usedCoupon_form'),
    path('user/',views.user_check, name='user'),
    path('user_form/',views.UserField.as_view(),name='user_form'),
    path('userAddress/',views.userAddress_check, name='userAddress'),
    path('userAddress_form/',views.UserAddressField.as_view(),name='userAddress_form'),
    path('userOrder/',views.userOrder_check, name='userOrder'),
    path('userOrder_form/',views.UserOrderField.as_view(),name='userOrder_form'),
    path("userOrderdelete/",views.DeleteUserOrder.as_view(),name="Delete_userOrder"),
    path("edituserOrder/<int:id>" ,views.EditUserOrder.as_view(),name="Edit_userOrder"),
    path('userWishlist/',views.userWishlist_check, name='userWishlist'),
    path('userWishlist_form/',views.UserWishlistField.as_view(),name='userWishlist_form'),
    path("userWishlistdelete/",views.DeleteuserWishlist.as_view(),name="Delete_userWishlist"),
    

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/shopping_mart/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
 
app_name = 'customAdminPanel'
app_name = 'G_shopper'

urlpatterns = [
    path('adminpanel/', include('customAdminPanel.urls')),
    path('admin/',admin.site.urls,name='django-admin'),
    path('', include('G_shopper.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/customAdminPanel/templates/model_form/banner_form.html
{% extends 'starter.html' %}

{% block content %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<script src="/static/dist/js/customs.js"></script>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add Banner</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6" style="position: relative; left: 300px;">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add Banner</h3>
            </div>
            <form action="{% url 'customAdminPanel:banner_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="required">
                  <label for="banner_name">Banner name</label>
                  {{ form.banner_name }}
                  {{form.errors.banner_name}}
                </div><br>
                <div class="required">
                  <label for="banner_path">Banner Path</label>
                  {{ form.banner_path }}
                </div><br>
                <div class="form-check">
                  <label class="form-check-label" for="status">Check me out</label>
                  {{ form.status }}
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" id="myWish"  class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:banner' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function () {
    setNavBar()
  });

  // set navebar
  function setNavBar() {
    $(".nav-link").removeClass("active")
    $(".banner-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/category_form.html
{% extends 'starter.html' %}

{% block content %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add Category</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6" style="position: relative; left: 300px;">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add Category</h3>
            </div>
            <form action="{% url 'customAdminPanel:category_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="required">
                  <label for="name">category name</label>
                  {{ form.name }}
                </div><br>
                <div >
                  <label for="parent_id">Parent Id</label>
                  {{ form.parent_id }}
                </div><br>
                <!-- <div class="form-group">
                    <label for="parent_id">created by</label>
                    {{ form.created_by }}
                  </div> -->
                  <!-- <div class="form-group">
                    <label for="parent_id">modify by</label>
                    {{ form.modify_by }}
                  </div> -->
                <div class="form-check">
                  <label class="form-check-label" for="status">Check me out</label>
                  {{ form.status }}
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:category' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".category-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/cms_form.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add Cms</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-11" style="left: 50px;">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add Cms</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <div class="card-body" style="width:100%; overflow: scroll;">
              <!-- <table id="example2" class="table table-bordered table-hover" style="width:2000px;"> -->
            <form action="{% url 'customAdminPanel:cms_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="required">
                  <label for="banner_name">Title</label>
                  {{ form.title }}
                </div>
                <div class="required">
                  <label for="Content" >content</label><br>
                  {{ form.content }}
                </div>
                <div class="required">
                  <label  for="meta_title">Meta title</label><br>
                  {{ form.meta_title }}
                </div>
                <div class="required">
                  <label for="meta_description">Meta Description</label><br>
                  {{ form.meta_description }}
                </div>
                <div class="required">
                  <label for="meta_keywords">Meta Keywords</label><br>
                  {{ form.meta_keywords }}
                </div>

              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:cms' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
            <!-- </table> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".cms-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/email_form.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Update Email</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-11" style="left: 50px;">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add Email</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{% url 'customAdminPanel:email_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="form-group required">
                  <label for="title">title</label>
                  {{ form.title }}
                </div>
                <div class="form-group required">
                  <label for="subject">subject</label>
                  {{ form.subject }}
                  <!-- <div class="input-group">
                      <div class="custom-file">
                        <label class="custom-file-label" for="banner_path">Choose file</label>
                        {{ form.banner_path }}
                      </div>
                    </div> -->
                </div>
                <div class="form-check required">
                  <label for="content">content</label>
                  {{ form.content }}
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:email' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".email-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/productAttributesAssoc_form.html
{% extends 'starter.html' %}

{% block content %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add productAttributesAssoc</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6" style="position: relative; left: 300px;">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add productAttributesAssoc</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{% url 'customAdminPanel:productAttributesAssoc_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="form-group required">
                  <label for="product id">product id</label>
                  {{ form.product_id }}
                </div>
                <div class="form-group required">
                  <label for="product_attribute_id">Attribute id</label>
                  {{ form.product_attribute_id }}
                </div>
                <div class="form-check required">
                  <label class="form-check-label" for="product_attribute_value">Attribute value</label>
                  {{ form.product_attribute_value }}
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:productAttributesAssoc' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".productAttributesAssoc-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/productAttributesValues_form.html
{% extends 'starter.html' %}

{% block content %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add productAttributesValues</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6" style="position: relative; left: 300px;">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add productAttributesValues</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{% url 'customAdminPanel:productAttributesValues_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="form-group required">
                  <label for="product_attribute_id">Attribute id</label>
                  {{ form.product_attribute_id }}
                </div>
                <div class="form-group required">
                  <label for="attribute_value">Attribute value</label>
                  {{ form.attribute_value }}
                </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:productAttributesValues' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".productAttributesValues-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/productCategory_form.html
{% extends 'starter.html' %}

{% block content %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add productCategory</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6" style="position: relative; left: 300px;">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add productCategory</h3>
            </div>
            <form action="{% url 'customAdminPanel:productCategory_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="form-group required">
                  <label for="product_id">Product id</label>
                  {{ form.product_id }}
                </div>
                <div class="form-group required">
                  <label for="category_id">Category id</label>
                  {{ form.category_id }}
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:productCategory' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".productCategory-menu").addClass("active")
  }
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/model_form/productImages_form.html
{% extends 'starter.html' %}

{% block content %}
<style>
  .required::before {
    content:" *";
    color: red;
  }
</style>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1>General Form</h1> -->
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add product</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6" style="position: relative; left: 300px;">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add product</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{% url 'customAdminPanel:productImages_form' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="card-body">
                <div class="form-group">
                  <label for="image_path">Image name</label>
                  {{ form.image_path }}
                </div>
                <div class="form-group">
                  <label for="status">Status</label>
                  {{ form.status }}
                </div>
                <div class="form-group">
                  <label for="product_id">Product id</label>
                  {{ form.product_id }}
                </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'customAdminPanel:productImages' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
      setNavBar()
  });

  // set navebar
  function setNavBar(){ 
      $(".nav-link").removeClass("active")
      $(".productImages-menu").addClass("active")
  }
</script>
{% endblock %}