shopping_mart/G_shopper/urls.py
from django.urls import path 
from G_shopper import views
from .views import  PasswordsChangeView
from django.contrib.auth import views as auth_views



app_name = 'G_shopper'

urlpatterns = [
    path('login/', views.userLogin, name='login'),
    # path('',views.base_page,name='base'),
    path('home/',views.home_page,name='home'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('loggedout/',views.logoutuser,name='loggedout'),
    path('registration/',views.UserRegister.as_view(),name='register'),
    path('mycart/',views.add_cart,name='cart'),
    path('cart/',views.cart_list,name='addcart'),
    path('deletefromcart/',views.delete_cart_item,name='delete-from-cart'),
    path('updatecart/',views.update_cart_item,name='update-cart'),
    path('deleteCart/',views.DeleteCart.as_view(),name='DeleteCart'),
    path('add-wishlist/',views.add_wishlist, name='add_wishlist'),
    path('my-wishlist/',views.my_wishlist, name='my_wishlist'),
    path("delete/",views.DeleteWishlist.as_view(),name="DeleteWishlist"),
    path('product/<int:product_id>',views.product_detail, name='product_detail'),
    path('coupon/',views.couponcalculate, name='couponcal'),
    path('checkout/',views.checkout,name='checkout'),
    path('address/',views.Add_address.as_view(),name='address'),    
    path('placeorder/',views.placeorder,name='placeorder'),
    path('stripe/',views.stripe_order,name='stripe'),
    path('cod/',views.cashondelivery,name='cod'),
    # path('category/',views.category_filter,name='category'),
    path('price/',views.price_filter,name='price'),
    # path('filter/',views.filter,name='filter'),
    path('order_track/',views.tracking_order,name='order_track'),
    path('check_order/',views.check_order,name='check_order'),
    path('contact/',views.contact_us,name='contact'),
    path('my_order/',views.my_order,name='my_order'),
    path('detailed_order/<int:order_id>',views.detailed_order.as_view(),name='detailed_order'),
    path('my_account/',views.my_account,name='my_account'),
    path('edit-profile/',views.edit_profile, name='edit-profile'),
    path('password/',PasswordsChangeView.as_view(template_name='changepassword.html'),name='password'),
    path('password_success',views.password_success,name='password_success'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('about_us/',views.cms_content,name='about_us'),
    path('privacy_policy/',views.privacy_policy,name='privacy_policy'),
    path('mail_template/',views.mail_template,name='mail_template'),
    path('order_mail_template/',views.order_mail_template,name='order_mail_template'),

    ]

shopping_mart/shopping_mart/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
 
app_name = 'customAdminPanel'
app_name = 'G_shopper'

urlpatterns = [
    path('adminpanel/', include('customAdminPanel.urls')),
    path('admin/',admin.site.urls,name='django-admin'),
    path('', include('G_shopper.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/G_shopper/models.py
from django.db import models

# Create your models here.

shopping_mart/customAdminPanel/models.py
from django.contrib.auth.models import Group
from django.db import models
from django_mysql.models import EnumField
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField



class User(AbstractUser):
    phone = models.CharField(max_length=13,null = True)
    # first_name = models.CharField(max_length=45)
    # last_name = models.CharField(max_length=45)
    # email = models.CharField(max_length=45)
    # password = models.CharField(max_length=45)
    # created_date = models.DateTimeField(auto_now_add=True)
    # # to_token = models.CharField(max_length=100)
    # # twitter_token = models.CharField(max_length=100)
    # # google_token = models.CharField(max_length=100)
    # group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='user_group')
    # specify_role = [('M','manager'),('C','customer'),('A','admin')]
    # role = models.CharField(max_length=10, choices=specify_role,default='')
    


    class Meta:
        verbose_name = "User"
        verbose_name_plural = "User"

class Configuration(models.Model):
    conf_key = models.CharField(max_length=45)
    conf_value = models.CharField(max_length=100)
    created_by = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.IntegerField()
    modify_date = models.DateTimeField(auto_now=True)
    modify_status = models.BooleanField()

    def __str__(self):
        return self.Configuration

    class Meta:
        verbose_name = "Configuration"
        verbose_name_plural = "Configuration"
   

class Cms(models.Model):
    title = models.CharField(max_length=255)
    content =RichTextField(blank=True,null=True)
    meta_title = models.TextField()
    meta_description = models.TextField()
    meta_keywords = models.TextField()
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Cms_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Cms_modified_by')
    modify_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Cms"
        verbose_name_plural = "Cms" 

class Banners(models.Model):
    banner_name = models.CharField(max_length=50 , unique=True)
    banner_path = models.ImageField(upload_to='shop_mart/images',default="")
    status = models.BooleanField()


    class Meta:
        db_table = "customAdminPanel_banners"
        verbose_name = "Banners"
        verbose_name_plural = "Banners" 



class EmailTemplate(models.Model):
    title = models.CharField(max_length=45)
    subject = models.CharField(max_length=255)
    content = RichTextField(blank=True,null=True)
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='EmailTemplate_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='EmailTemplate_modified_by')
    modify_date = models.DateTimeField(auto_now=True)   

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "EmailTemplate"
        verbose_name_plural = "EmailTemplate"

class ContactUs(models.Model):
    name = models.CharField(max_length=45)
    email = models.EmailField(max_length=45)
    contact_no = models.CharField(max_length=45)
    message = models.TextField()
    note_admin = models.TextField()
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='ContactUs_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='ContactUs_modify_by')
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "ContactUs"
        verbose_name_plural = "ContactUs"

class Category(models.Model):
    name = models.CharField(max_length=100)
    parent_id = models.ForeignKey("self", null=True,blank=True,on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Category_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Category_modified_by')
    modify_date = models.DateTimeField(auto_now=True)
    status = models.BooleanField()

    def __str__(self):
            return self.name
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Category"


class Product(models.Model):
    name = models.CharField(max_length=100)
    sku = models.CharField(max_length=45)
    short_description = models.TextField()
    long_description = models.TextField()
    price = models.FloatField()
    special_price_from = models.DateTimeField(auto_now_add=True)
    special_price_to = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField()
    quantity = models.IntegerField()
    meta_title = models.TextField()
    meta_description = models.TextField()
    meta_keywords = models.TextField()
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Product_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Product_modified_by')
    modify_date = models.DateTimeField(auto_now_add=True)
    is_featured = models.BooleanField()
    # image = models.ImageField(upload_to='shop_mart/product_images',default="")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Product" 


class ProductCategories(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.ProductCategories

    class Meta:
        verbose_name = "ProductCategories"
        verbose_name_plural = "ProductCategories"

class ProductImages(models.Model):
    image_path = models.ImageField(upload_to='shop_mart/product_images',default="")
    status = models.BooleanField()
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='ProductImages_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='ProductImages_modified_by')
    modify_date = models.DateTimeField(auto_now=True)   
    product_id = models.ForeignKey(Product,on_delete=models.CASCADE,blank=True)

    # def __str__(self):
    #     return self.image_path

    class Meta:
        verbose_name = "ProductImages"
        verbose_name_plural = "ProductImages"


class UserWishList(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product,on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.

    class Meta:
        verbose_name = "UserWishList"
        verbose_name_plural = "UserWishList"


class UserAddress(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    address_1 = models.CharField(max_length=100)
    address_2 = models.CharField(max_length=100)
    city = models.CharField(max_length=45)
    state = models.CharField(max_length=45)
    country = models.CharField(max_length=45)
    zip_code = models.CharField(max_length=45)

    def __str__(self):
        return self.address_1

    class Meta:
        verbose_name = "UserAddress"
        verbose_name_plural = "UserAddress"


class Coupon(models.Model):
    code = models.CharField(max_length=45)
    percent_off = models.FloatField()
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Coupon_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='Coupon_modified_by')
    modify_date = models.DateTimeField(auto_now=True) 
    no_of_user = models.IntegerField()

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "Coupon"
        verbose_name_plural = "Coupon"  


class CouponsUsed(models.Model):
    user_id = models.IntegerField() 
    order_id = models.IntegerField() 
    created_date = models.DateField()
    coupon_id = models.ForeignKey(Coupon,on_delete=models.CASCADE)

    def __str__(self):
        return self.UsedCoupons

    class Meta:
        verbose_name = "UsedCoupons"
        verbose_name_plural = "UsedCoupons"



class PaymentGateway(models.Model):
    name = models.CharField(max_length=45)
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='PaymentGateway_created_by')
    created_date = models.DateTimeField(auto_now_add=True)
    modify_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='PaymentGateway_modified_by')
    modify_date = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "PaymentGateway"
        verbose_name_plural = "PaymentGateway"  



class ProductAttributes(models.Model):
    name = models.CharField(max_length=45)
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='ProductAttributes_created_by')
    created_date = models.DateTimeField(auto_now_add=True)

shopping_mart/G_shopper/templates/register/address_form.html
{% extends 'base.html' %}

{% block content %}
<div class="shopper-informations">
    <div class="row">
        <div class="col-sm-3">
            <div class="shopper-info">
            </div>
        </div>
        

        <div class="col-sm-5 clearfix">
            <div class="bill-to">
                <h1 style="text-align:center;">Add Your Address Here.</h1>
                <div class="form-one">
                    <form action="" method="post" value="Add Address">
                        {% csrf_token %}
                        <label for="user_id">user_id</label> <br>
                        <textarea name="" id="" cols="1" rows="1" disabled>{{ request.user}}</textarea><b></b> <br>
                        <label for="address_1">address_1</label>
                        {{ form.address_1 }}
                        <label for="address_2">address_2</label>
                        {{ form.address_2 }}
                        <label for="city">city</label>
                        {{ form.city }}
                        <label for="country">country</label>
                        {{ form.country }}
                        <label for="state">state</label>
                        {{ form.state }}
                        <label for="zip_code">zip_code</label>
                        {{ form.zip_code }}
                        <button type="submit" class="btn btn-primary">Add Address</button>   
                        
                    </form>
                    <a href="{% url 'G_shopper:home' %}"><button class="btn btn-primary">Cancel</button></a> 
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="order-message">
            </div>
        </div>
    </div>
</div>

{% endblock %}

shopping_mart/G_shopper/templates/register/login.html
{% extends 'based.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-4 col-sm-offset-3">
            <div class="login-form">
                <!--login form-->
                <h2>Login to your account</h2>
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} " id="msg" role="alert">
                    {{ message }}</div>
                    {% endfor %}
                    <form action="{%url 'G_shopper:login' %}" method="post" name="Login" ,value="Login">
                        {% csrf_token %}
                        <label for="usernameLogin" name="Login" ,value="Login" id="username">Email</label>
                        {{ form.username }}
                        {{ form.errors.username }}
                        <label for="passwordlogin" name="Login" ,value="Login" id="password1">Password</label>
                        {{ form.password1 }}
                        {{ form.errors.password1 }}
                        <button type="submit" class="btn btn-default" name="Login" ,value="Login" onclick="ValidateEmail(document.form1.text1)">Login</button>
                    </form><br>
                    <a href="{% url 'G_shopper:password_reset' %}">Forgot Password</a>
                </div><br>
                <!--/login form-->
                <label>For Registration? </label>
                <a href="{% url 'G_shopper:register' %}">Register</a>
            </div>
        </div>
    </div>


    {% endblock %}

shopping_mart/G_shopper/templates/register/products_list.html
{% for prod in data %}
<div class="col-sm-4 product-box">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <!-- <img src="images/home/product1.jpg" alt="" /> -->
                <img src="{{prod.productimages_set.first.image_path.url}}" alt="" />
                <input type="hidden" class="product-image-{{prod.id}}"
                    value="{{prod.productimages_set.first.image_path.url}}" />
                <th>Rs <span class="product-price-{{prod.id}}">{{prod.price}}</span></th>
                <p>{{prod.name}}</p>
                <input type="hidden" class="product_id-{{prod.id}}" value="{{prod.id}}">
                <input type="hidden" class="meta_title-{{prod.id}}" value="{{prod.meta_title}}">
                <button class="btn btn-default add-to-cart" id="{{prod.id}}"><i
                        class="fa fa-shopping-cart addcart"></i>Add to cart</button>
            </div>
            <div class="product-overlay">
                <div class="overlay-content">
                    <h2>Rs{{prod.price}}</h2>
                    <p>{{prod.name}}</p>
                    <button class="btn btn-default add-to-cart" id="{{prod.id}}"><i
                            class="fa fa-shopping-cart addcart"></i>Add to cart</button>
                    <div class="cart_quantity_button submitWidget submitWidget-{{prod.id}}">
                        <input type="button" onclick="decrementValue('{{prod.id}}')"
                            value=" - " />
                        <input type="text" id="product-qty-{{prod.id}}" name="quantity"
                            value="1" maxlength="2" max="10" size="1" readonly />
                        <input type="button" onclick="incrementValue('{{prod.id}}')"
                            value="+" />
                    </div>
                </div>
            </div>
        </div>
        <div class="choose">
            {% if user.is_authenticated %}
            <ul class="nav nav-pills nav-justified">
                <li><button class="btn btn-default add-wishlist" data-product="{{prod.id}}">
                        Add to wishlist</button></li>
                {% else %}
                <li><button class="btn btn-default disabled" data-product="{{prod.id}}">
                        Add to wishlist</button></li>
            </ul>
            {% endif %}
        </div>
    </div>
</div>{% endfor %}

shopping_mart/G_shopper/templates/register/register_form.html
{% extends 'base.html' %}

{% block content %}

<!-- <section id="form"> -->
	<!--form-->
	<h2 style="text-align:center;">Registration Form.</h2>
	<div class="container">
		<div class="row">
			<div class="col-sm-5 col-sm-offset-4">
				<div class="signup-form">
					<!--sign up form-->
					<h2>New User Signup!</h2>
					{% for message in messages %}
                <div class="alert alert-{{ message.tags }} " id="msg" role="alert">
                    {{ message }}</div>
                    {% endfor %}
					<form action="" method="post" name="Register" value="Register">
						{% csrf_token %}
						<label for="first_name">First Name</label>
						{{ form.first_name }}
						<label for="last_name">Last Name</label>
						{{ form.last_name }}
						<label for="email" >Email</label>
						{{ form.email }}
						{{ form.errors.email }}
						<label for="username" name="Register" value="Register">Username</label>
						{{ form.username }}
						{{ form.errors.username }}
						<label for="password1" name="Register" value="Register">Password</label>
						{{ form.password1 }}
						{{ form.errors.password1 }}
						<label for="password2">confirm password</label>
						{{ form.password2 }}
						{{ form.errors.password2 }}
						<button type="submit" class="btn btn-default" name="Register" value="Register">Signup</button>
					</form>
				</div>
				<!--/sign up form-->
				<br>
				<label>If already have an account</label>
				<a href="{% url 'G_shopper:login' %}">Log In</a>
			</div>
		</div>
	</div>

<!--/form-->

{% endblock %}