shopping_mart/G_shopper/urls.py
from django.urls import path 
from G_shopper import views
from .views import  PasswordsChangeView
from django.contrib.auth import views as auth_views



app_name = 'G_shopper'

urlpatterns = [
    path('login/', views.userLogin, name='login'),
    # path('',views.base_page,name='base'),
    path('home/',views.home_page,name='home'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('loggedout/',views.logoutuser,name='loggedout'),
    path('registration/',views.UserRegister.as_view(),name='register'),
    path('mycart/',views.add_cart,name='cart'),
    path('cart/',views.cart_list,name='addcart'),
    path('deletefromcart/',views.delete_cart_item,name='delete-from-cart'),
    path('updatecart/',views.update_cart_item,name='update-cart'),
    path('deleteCart/',views.DeleteCart.as_view(),name='DeleteCart'),
    path('add-wishlist/',views.add_wishlist, name='add_wishlist'),
    path('my-wishlist/',views.my_wishlist, name='my_wishlist'),
    path("delete/",views.DeleteWishlist.as_view(),name="DeleteWishlist"),
    path('product/<int:product_id>',views.product_detail, name='product_detail'),
    path('coupon/',views.couponcalculate, name='couponcal'),
    path('checkout/',views.checkout,name='checkout'),
    path('address/',views.Add_address.as_view(),name='address'),    
    path('placeorder/',views.placeorder,name='placeorder'),
    path('stripe/',views.stripe_order,name='stripe'),
    path('cod/',views.cashondelivery,name='cod'),
    # path('category/',views.category_filter,name='category'),
    path('price/',views.price_filter,name='price'),
    # path('filter/',views.filter,name='filter'),
    path('order_track/',views.tracking_order,name='order_track'),
    path('check_order/',views.check_order,name='check_order'),
    path('contact/',views.contact_us,name='contact'),
    path('my_order/',views.my_order,name='my_order'),
    path('detailed_order/<int:order_id>',views.detailed_order.as_view(),name='detailed_order'),
    path('my_account/',views.my_account,name='my_account'),
    path('edit-profile/',views.edit_profile, name='edit-profile'),
    path('password/',PasswordsChangeView.as_view(template_name='changepassword.html'),name='password'),
    path('password_success',views.password_success,name='password_success'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('about_us/',views.cms_content,name='about_us'),
    path('privacy_policy/',views.privacy_policy,name='privacy_policy'),
    path('mail_template/',views.mail_template,name='mail_template'),
    path('order_mail_template/',views.order_mail_template,name='order_mail_template'),

    ]

shopping_mart/customAdminPanel/urls.py
from os import stat
from unicodedata import category
from django.urls import path 
from customAdminPanel import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required 

app_name = 'customAdminPanel'

urlpatterns = [
    path('login/', views.adminLogin, name='admin_login'),
    path('',views.index,name='index'),
    path('logout/',views.logoutUser,name='logoutuser'),
    path('banner/',views.banner_check, name='banner'),
    path('banner_form/',views.BannerField.as_view(),name='banner_form'),
    path("delete/",views.DeleteBanner.as_view(),name="Delete"),
    path("edit/<int:id>" ,views.EditBanner.as_view(),name="Edit"),
    path('category/',views.category_check, name='category'),
    path('category_form',views.CategoryField.as_view(),name='category_form'),
    path("Delete_category/",views.DeleteCategory.as_view(),name="Delete_category"),
    path("editCategory/<int:id>" ,views.EditCategory.as_view(),name="EditCategory"),
    path('cms/',views.cms_check, name='cms'),
    path('cms_form/',views.CmsField.as_view(),name='cms_form'),
    path("Delete_cms/",views.DeleteCms.as_view(),name="Delete_cms"),
    path("editCms/<int:id>" ,views.EditCms.as_view(),name="EditCms"),
    path('configuration/',views.configuration_check, name='configuration'),
    path('configuration_form/',views.ConfigurationField.as_view(),name='configuration_form'),
    path('contactUs/',views.contactUs_check, name='contactUs'),
    path('contactUs_form/',views.ContactUsField.as_view(),name='contactUs_form'),
    path('coupon/',views.coupon_check, name='coupon'),
    path('coupon_form/',views.CouponField.as_view(),name='coupon_form'),
    path("coupondelete/",views.DeleteCoupon.as_view(),name="Delete_coupon"),
    path("editCoupon/<int:id>" ,views.EditCoupon.as_view(),name="EditCoupon"),
    path('email/',views.email_check, name='email'),
    path('email_form/',views.EmailField.as_view(),name='email_form'),
    path('emaildelete/',views.DeleteEmail.as_view(),name='emaildelete'),
    path("editEmail/<int:id>" ,views.EditEmail.as_view(),name="EditEmail"),
    path('orderDetail/',views.orderDetail_check, name='orderDetail'),
    path('orderDetail_form/',views.OrderDetailField.as_view(),name='orderDetail_form'),
    path('detail_order/<int:order_id>',views.detail_order.as_view(),name='detail_order'),
    path('paymentGateway/',views.paymentGateway_check, name='paymentGateway'),
    path('paymentGateway_form/',views.PaymentGatewayField.as_view(),name='paymentGateway_form'),
    path('product/',views.product_check, name='product'),
    path('product_form/',views.ProductField.as_view(),name='product_form'),
    path("productdelete/",views.DeleteProduct.as_view(),name="Delete_product"),
    path("editProduct/<int:id>" ,views.EditProduct.as_view(),name="EditProduct"),
    path('productAttributes/',views.productAttributes_check, name='productAttributes'),
    path('productAttributes_form/',views.ProductAttributesField.as_view(),name='productAttributes_form'),
    path("productAttributesdelete/",views.DeleteProductAttributes.as_view(),name="Delete_productAttributes"),
    path("editProductAttributes/<int:id>" ,views.EditProductAttributes.as_view(),name="EditProductAttributes"),
    path('productAttributesAssoc/',views.productAttributesAssoc_check, name='productAttributesAssoc'),
    path('productAttributesAssoc_form/',views.ProductAttributesAssocField.as_view(),
    name='productAttributesAssoc_form'),
    path('ajax/productAttributesValue/',views.getAttributeValues, name='productAttributesValue'),
    path('productAttributesValues/',views.productAttributesValues_check, name='productAttributesValues'),
    path('productAttributesValues_form/',views.ProductAttributesValuesField.as_view(),name='productAttributesValues_form'),
    path('productCategory/',views.productCategory_check, name='productCategory'),
    path('productCategory_form/',views.ProductCategoryField.as_view(),name='productCategory_form'),
    path("productCategorydelete/",views.DeleteProductCategory.as_view(),name="Delete_productCategory"),
    path("editProductCategory/<int:id>" ,views.EditProductCategory.as_view(),name="EditProductCategory"),
    path('productImages/',views.productImages_check, name='productImages'),
    path('productImages_form/',views.ProductImagesField.as_view(),name='productImages_form'),
    path("productImagesdelete/",views.DeleteProductImage.as_view(),name="Delete_productImage"),
    path("editProductImage/<int:id>" ,views.EditProductImage.as_view(),name="EditProductImage"),
    path('usedCoupon/',views.usedCoupon_check, name='usedCoupon'),
    path('usedCoupon_form/',views.UsedCouponField.as_view(),name='usedCoupon_form'),
    path('user/',views.user_check, name='user'),
    path('user_form/',views.UserField.as_view(),name='user_form'),
    path('userAddress/',views.userAddress_check, name='userAddress'),
    path('userAddress_form/',views.UserAddressField.as_view(),name='userAddress_form'),
    path('userOrder/',views.userOrder_check, name='userOrder'),
    path('userOrder_form/',views.UserOrderField.as_view(),name='userOrder_form'),
    path("userOrderdelete/",views.DeleteUserOrder.as_view(),name="Delete_userOrder"),
    path("edituserOrder/<int:id>" ,views.EditUserOrder.as_view(),name="Edit_userOrder"),
    path('userWishlist/',views.userWishlist_check, name='userWishlist'),
    path('userWishlist_form/',views.UserWishlistField.as_view(),name='userWishlist_form'),
    path("userWishlistdelete/",views.DeleteuserWishlist.as_view(),name="Delete_userWishlist"),
    

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/shopping_mart/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
 
app_name = 'customAdminPanel'
app_name = 'G_shopper'

urlpatterns = [
    path('adminpanel/', include('customAdminPanel.urls')),
    path('admin/',admin.site.urls,name='django-admin'),
    path('', include('G_shopper.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_mart/customAdminPanel/templates/banner.html
{% extends 'starter.html' %}

{% block content %}
<script src="/static/dist/js/customs.js"></script>
<div class="content-wrapper">
  <section class="content">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <div class="card">
            <div class="col-sm-12">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Banner</li>
              </ol>
            </div>
            <form action="{% url 'customAdminPanel:banner_form' %}">
              <!-- <button  type="submit" class="btn btn-primary btn-block">Sign Out</button> -->
              <button style="float: right; width: 150px; height: 40px;" type="submit"
                class="btn btn-block btn-primary">Add Banner</button>
            </form> <br>
            {% for msg in messages %}
            {% if msg.tags == 'error' %}
            <div class="alert alert-danger" id="error-alert" role="alert">
              {{msg}}            
            </div>
            {% else %}
            <div class="alert alert-success" id="success-alert" role="alert">
              {{msg}}
            </div>
            {% endif %}
          {% endfor %}
            <div class="card-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Category</th>
                    <!-- <th>Image Name</th> -->
                    <th>Status</th>
                    <th>Image views</th>
                    <th scope="col" colspan="2">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for ban in form %}
                  <tr>
                    <!-- <td>{{ban.id}}</td> -->
                    <td>{{ban.banner_name}}</td>
                    <!-- <td>{{ban.banner_path}}</td> -->
                    <td>{{ban.status}}</td>
                    {% if ban.banner_path %}
                    <td>
                      <img src="{{ ban.banner_path.url }}" alt="" style="height: 30px" width="30px">
                    </td>
                    {% else %}
                    <td>
                      <img src="/shop_mart/shopping_mart/media/shop_mart" style="height: 30px" width="30px" ;>
                    </td>
                    {% endif %}
                    <td>
                      <a href="{% url 'customAdminPanel:Edit' ban.id %}"><button class="btn btn-default btn-sm"><i
                            class="fas fa-edit"></i></button></a>
                    </td>
                    <td>
                      <form action="{% url 'customAdminPanel:Delete' %}" method="POST">
                              {% csrf_token %}
                              <button type="button" value="Delete" class="btn btn-danger btn-sm"
                                  data-toggle="modal" data-target="#deletemodal-{{ban.id}}">
                                  Delete
                              </button>
                              <input type="hidden" name="id" value={{ban.id}}>
                              <div class="modal fade" id="deletemodal-{{ban.id}}">
                                  <div class="modal-dialog">
                                      <div class="modal-content">
                                          <div class="modal-header">
                                              <h4 class="modal-title">Delete</h4>
                                              <button type="button" class="close" data-dismiss="modal"
                                                  aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                              </button>
                                          </div>
                                          <div class="modal6-body">
                                              <h4>Do you want to delete this data??</h4>
                                          </div>
                                          <div class="modal-footer justify-content-between">
                                              <button type="button" class="btn btn-default"
                                                  data-dismiss="modal">Close</button>
                                              <button type="submit" class="btn btn-danger">Ok
                                              </button>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </form>
                      </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<!-- <script type="text/javascript">
  $(document).ready(function () {
    $("ul li a").click(function(){  
      // $('a.active').each(function(){
      $('li a').find(".active").removeClass('active');
      $(this).parent().addClass('active');
    });
  });
</script> -->
{% endblock %}

{% block script %}
<script>
  $(document).ready(function () {
    setNavBar()
  });

  // set navebar
  function setNavBar() {
    $(".nav-link").removeClass("active")
    $(".banner-menu").addClass("active")
  }
</script>
<script>
  $(document).ready(function() {
  setTimeout(function() {
    $('#success-alert').fadeOut('fast');
}, 2000);
    });
</script>
<script>
  $(document).ready(function() {
  setTimeout(function() {
    $('#error-alert').fadeOut('fast');
}, 2000);
    });
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/category.html
{% extends 'starter.html' %}

{% block content %}

<div class="content-wrapper">
  <section class="content">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <div class="card">
            <div class="col-sm-12">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Category</li>
              </ol>
            </div>
            <form action="{% url 'customAdminPanel:category_form' %}">
              <!-- <button  type="submit" class="btn btn-primary btn-block">Sign Out</button> -->
              <button style="float: right; width: 150px; height: 40px;" type="submit"
                class="btn btn-block btn-primary">Add Category</button>
            </form> <br>
            {% for msg in messages %}
            {% if msg.tags == 'error' %}
            <div class="alert alert-danger" id="error-alert" role="alert">
              {{msg}}            
            </div>
            {% else %}
            <div class="alert alert-success" id="success-alert" role="alert">
              {{msg}}
            </div>
            {% endif %}
          {% endfor %}
            <div class="card-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Category Name</th>
                    <!-- <th>parent_id</th> -->
                    <th>Created by</th>
                    <th>Created date</th>
                    <th>modify by</th>
                    <th>modify date</th>
                    <th>Status</th>
                    <th scope="col" colspan="2">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for i in obj %}
                  <tr>
                    <td>{{i.name}}</td>
                    <!-- {% if i.parent_id %}
                    <td>{{i.parent_id}}</td>
                    {% else %} -->
                    <!-- <td>-</td>
                    {% endif %} -->
                    <td>{{i.created_by}}</td>
                    <td>{{i.created_date}}</td>
                    <td>{{i.modify_by}}</td>
                    <td>{{i.modify_date}}</td>
                    <td>{{i.status}}</td>
                    <td>
                      <a href="{% url 'customAdminPanel:EditCategory' i.id %}"><button class="btn btn-default btn-sm"><i
                            class="fas fa-edit"></i></button></a>
                    </td>
                    <td>
                      <form action="{% url 'customAdminPanel:Delete_category' %}" method="POST">
                              {% csrf_token %}
                              <button type="button" value="Delete" class="btn btn-danger btn-sm"
                                  data-toggle="modal" data-target="#deletemodal-{{i.id}}">
                                  Delete
                              </button>
                              <input type="hidden" name="id" value={{i.id}}>
                              <div class="modal fade" id="deletemodal-{{i.id}}">
                                  <div class="modal-dialog">
                                      <div class="modal-content">
                                          <div class="modal-header">
                                              <h4 class="modal-title">Delete</h4>
                                              <button type="button" class="close" data-dismiss="modal"
                                                  aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                              </button>
                                          </div>
                                          <div class="modal6-body">
                                              <h4>Do you want to delete this data??</h4>
                                          </div>
                                          <div class="modal-footer justify-content-between">
                                              <button type="button" class="btn btn-default"
                                                  data-dismiss="modal">Close</button>
                                              <button type="submit" class="btn btn-danger">Ok
                                              </button>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </form>
                      </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

{% block script %}
<script>
  $(document).ready(function () {
    setNavBar()
  });

  // set navebar
  function setNavBar() {
    $(".nav-link").removeClass("active")
    $(".category-menu").addClass("active")
  }
</script>
<script>
  $(document).ready(function() {
  setTimeout(function() {
    $('#success-alert').fadeOut('fast');
}, 2000);
    });
</script>
<script>
  $(document).ready(function() {
  setTimeout(function() {
    $('#error-alert').fadeOut('fast');
}, 2000);
    });
</script>
{% endblock %}

shopping_mart/customAdminPanel/templates/contactUs.html
{% extends 'starter.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="col-sm-12">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">contactUs</li>
                            </ol>
                        </div>
                        <!-- <form action="{% url 'customAdminPanel:contactUs_form' %}">
                            <button  type="submit" class="btn btn-primary btn-block">Sign Out</button>
                            <button style="float: right; width: 150px; height: 40px;" type="submit"
                                class="btn btn-block btn-primary">Add</button>
                        </form> -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                              <thead>
                                <tr>
                                  <th>Name</th>
                                  <th>Email</th>
                                  <th>Message</th>
                                  <th>Created by</th>
                                  <th>Created date</th>
                                  <th>modify by</th>
                                  <th>modify date</th>
                                  <!-- <th scope="col" colspan="2">Action</th> -->
                                </tr>
                              </thead>
                              <tbody>
                                {% for i in form %}
                                <tr>
                                  <td>{{i.name}}</td>
                                  <td>{{i.email}}</td>
                                  <td>{{i.message}}</td>
                                  <td>{{i.created_by}}</td>
                                  <td>{{i.created_date}}</td>
                                  <td>{{i.modify_by}}</td>
                                  <td>{{i.modify_date}}</td>
                                  <td>{{i.status}}</td>
                                  <!-- <td>
                                    <a href="{% url 'customAdminPanel:EditCategory' i.id %}"><button class="btn btn-default btn-sm"><i
                                          class="fas fa-edit"></i></button></a>
                                  </td>
                                  <td>
                                      <button type="submit" value="Delete" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deletemodal">
                                        Delete
                                      </button>
                                      <div class="modal fade" id="deletemodal">
                                        <div class="modal-dialog">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h4 class="modal-title">Delete</h4>
                                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                              </button>
                                            </div>
                                            <form action="{% url 'customAdminPanel:Delete_category' %}" method="POST">
                                              {% csrf_token %}
                                              <div class="modal6-body">
                                                <input type="hidden" name="id" value={{i.id}}>
                                                <h4>Do you want to delete this data??</h4>
                                              </div>
                                              <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger">Ok
                                                </button>
                                              </div>
                                          </div>
                                        </div>
                                      </div>
                                      </form>
                                    </td> -->
                                </tr>
                                {% endfor %}
              
                              </tbody>
                            </table>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<!-- <script type="text/javascript">
  $(document).ready(function () {
    $("ul li a").click(function(){  
      // $('a.active').each(function(){
      $('li a').find(".active").removeClass('active');
      $(this).parent().addClass('active');
    });
  });
</script> -->
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        setNavBar()
    });

    // set navebar
    function setNavBar() {
        $(".nav-link").removeClass("active")
        $(".contactUs-menu").addClass("active")
    }
</script>

{% endblock %}

shopping_mart/customAdminPanel/templates/footer.html
{% block content %}
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
          Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
      </footer>
    {% endblock %}

shopping_mart/customAdminPanel/templates/user.html
{% extends 'starter.html' %}

{% block content %}

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="col-sm-12">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">user</li>
                            </ol>
                        </div>
                        <form action="{% url 'customAdminPanel:user_form' %}">
                            <!-- <button  type="submit" class="btn btn-primary btn-block">Sign Out</button>
                            <button style="float: right; width: 150px; height: 40px;" type="submit"
                                class="btn btn-block btn-primary">Add</button> -->
                        </form>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                              <thead>
                                <tr>
                                  <th>Email Address</th>
                                  <th>Username</th>
                                  <!-- <th scope="col" colspan="2">Action</th> -->
                                </tr>
                              </thead>
                              <tbody>
                                {% for i in form %}
                                <tr>
                                  <td>{{i.email}}</td>
                                  <td>{{i.username}}</td>
                                  <!-- <td>
                                    <a href="{% url 'customAdminPanel:EditCategory' i.id %}"><button class="btn btn-default btn-sm"><i
                                          class="fas fa-edit"></i></button></a>
                                  </td> -->
                                  <!-- <td>
                                      <button type="submit" value="Delete" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deletemodal">
                                        Delete
                                      </button>
                                      <div class="modal fade" id="deletemodal">
                                        <div class="modal-dialog">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h4 class="modal-title">Delete</h4>
                                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                              </button>
                                            </div>
                                            <form action="{% url 'customAdminPanel:Delete_category' %}" method="POST">
                                              {% csrf_token %}
                                              <div class="modal6-body">
                                                <input type="hidden" name="id" value={{i.id}}>
                                                <h4>Do you want to delete this data??</h4>
                                              </div>
                                              <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger">Ok
                                                </button>
                                              </div>
                                          </div>
                                        </div>
                                      </div>
                                      </form>
                                    </td> -->
                                </tr>
                                {% endfor %}
              
                              </tbody>
                            </table>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<!-- <script type="text/javascript">
  $(document).ready(function () {
    $("ul li a").click(function(){  
      // $('a.active').each(function(){
      $('li a').find(".active").removeClass('active');
      $(this).parent().addClass('active');
    });
  });
</script> -->
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        setNavBar()
    });

    // set navebar
    function setNavBar() {
        $(".nav-link").removeClass("active")
        $(".user-menu").addClass("active")
    }
</script>
{% endblock %}